### ISSUE TITLE
Is this project working?

### ISSUE THREAD

**Issue by 4brunu** [guillermo-gerard/Twilio.Video.Android.Xamarin.Binding#1]
Hey,
Thanks for creating this binding.
It looks promising, is this working?
Do you need any help?
Thanks

**Comment by guillermo-gerard** [comment]
Hi Bruno,
Yes, it should work, you may remember that I've made one of the last contributions to Jorgen's (jorgen@woei.nl) repository. 
I'm referring to the one that was taken down, as you may know. I can see you on the email list.
Sadly, this repo lack of examples and even worse, I stopped my work on the project where I used this binding, so I guess I'm not going to update it soon.

**Comment by 4brunu** [comment]
Thanks for heads-up 👍

**Comment by 4brunu** [comment]
I'm looking for a solution for the bindings of Twilio Video SDK since the previous repo was taken down, and found this repo while searching for an alternative.
I closed this to avoid creating noise and you already answered to my questions 👍
